### ISSUE TITLE
[Brasília/DF] Luciano Junior

### ISSUE THREAD

**Issue by Ljuniorcode** [alinebastos/contrate-junior-estagio#103]
## Nome completo
Luciano Junior

## Localidade
Brasília - Asa Norte.

## Apresentação
Formei em redes de computadores, trabalhei com suporte e infraestrutura e atualmente estou focado em desenvolvimento web. Possuo conhecimentos em HTML, CSS, JAVASCRIPT e aprendendo NODEJS, REACTJS,  MySQL e GIT.  Já desenvolvi vários projetos por meio dos cursos realizados, estou procurando uma oportunidade na área de front-end para colocar em prática meus conhecimentos.

## Outras Informações
Cursos em andamento: devPleno.com;
Comunidades que participo no discord: Rocketseat, CollabCode, Erick Wendell Training e DevSuperior;
Tenha disponibilidade imediata em horários na parte da manhã, tarde e eventuais fins de semana.
Participo de várias lives que envolvem a tecnologia,  mercado, aprendizado e um pouco sobre o futuro delas, alguns canais são:
1 - Rocketseat - YouTube;
2 - Túlio Faria - comunidade fechada do curso devPleno;
3 - Marco Bruno - twitch.tv/marcobrunodev;

## Skills
- HTML
- CSS
- JavaScript
- ReactJS
- MySQL
- Git

## O que está procurando
- Júnior
- Freela

## Tipo de contratação
- PJ
- CLT
- Freela
- Temporário

## Contato
https://www.linkedin.com/in/luciano-junior-dev/

## Site
https://github.com/Ljuniorcode

**Comment by Ljuniorcode** [comment]
Entendo o motivo de ter fechado a issue... é 'apenas' para quem nunca teve experiência certo?

**Comment by alinebastos** [comment]
Isso, desculpa ter que fazer a regra valer a ferro e fogo, mas se eu abro uma exceção eu tenho que abrir pra todos.
