### ISSUE TITLE
[Monte Azul/MG] Eustáquio de Freitas Barbosa

### ISSUE THREAD

**Issue by eustaquiofreitas** [alinebastos/contrate-junior-estagio#124]
## Nome completo

Eustáquio de Freitas Barbosa

## Localidade

Monte Azul - MG

## Apresentação

Profissional em fase de migração como professor de matemática que busca oportunidade para aprender, desenvolver, adquiri experiência e agregar conhecimentos no qual obteve durante trajetória como docente.
  

## Outras Informações
Trabalho Home Office

## Skills
- NodeJs
- JavaScript
- HTML
- CSS
- Linux

## Áreas de Interesse

- [ ] Frontend
- [x] Backend
- [x] Fullstack
- [ ] Mobile
- [ ] UX
- [ ] DevOps
- [ ] Infra

## Tipo de contratação

- [ ] PJ
- [x] CLT
- [ ] Estágio
- [x] Júnior
- [ ] Freela

## Contato
- Currículo Lattes: http://lattes.cnpq.br/8152925267702772
- Linkdin: https://www.linkedin.com/in/eustaquiodefreitasbarbosa/

**Comment by alinebastos** [comment]
Oi Eustáquio, vou fechar a tua issue pois, por menor que seja, tu teve alguma experiência prévia, e nas regras está bem explícito que a issue seria fechado. Espero que tu entenda :)
