### ISSUE TITLE
[Volta Grande/MG] Thiago Alves

### ISSUE THREAD

**Issue by the-one-who-knoccks** [alinebastos/contrate-junior-estagio#13]
## Nome completo

Thiago Alves Bastos

## Localidade

Volta Grande - Minas Gerais

## Apresentação

Trabalhei por mais de 15 anos na área de TI como suporte. E há 1 ano e meio migrei para o desenvolvimento web/mobile utilizando React e React Native e também com back-end usando Node.js. Sou totalmente comprometido e me dou muito bem no trabalho em equipe. Estou sempre procurando aprender coisas novas.

## Outras Informações

Tenho total disponibilidade com horário e procuro trabalho remoto durante o período de pandemia.

## Skills

- JavaScript
- TypeScript
- HTML
- CSS
- ReactJS
- React Native
- Node.js
- MongoDB
- SQL
- Docker

## O que está procurando

- Estágio
- Júnior

## Tipo de contratação

- CLT
- Freela
- Estágio

## Contato

https://linkedin.com/in/thiagoalves89/

**Comment by alinebastos** [comment]
Oi Thiago, vou ter que fechar esta issue, pois o objetivo deste repositório é cadastrar pessoas que estão procurando a primeira oportunidade na área de TI, e como vi tu já tens experiência.

**Comment by the-one-who-knoccks** [comment]
Oi Aline. Entendo. Peço desculpas. Estou em um estágio, porém procuro meu
primeiro emprego como dev JR. Você tem algum repositório para vagas desse
tipo? Desde já grato.

**Comment by alinebastos** [comment]
Imagina, te entendo, é só pra manter a regra clara aqui, senão acaba perdendo o controle.
Tem este repositorio com empresas que contratam junior sem experiencia, dá uma vasculhada, manda curriculo pra todas :)

**Comment by the-one-who-knoccks** [comment]
Ok, muito obrigado e parabéns pela iniciativa. Te desejo  sucesso!
