### ISSUE TITLE
[Osasco/SP] Matheus Fernandes de Sá

### ISSUE THREAD

**Issue by SaMatheus** [alinebastos/contrate-junior-estagio#161]
## Nome completo

Matheus Fernandes de Sá

## Localidade

Osasco - São Paulo

## Apresentação

Depois de muito tempo pulando de empresa em empresa procurando um rumo, eu decidi tomar vergonha na cara e correr atrás do que eu AMO!
Sempre gostei muito de programação, mas achava difícil e que "programar era coisa pra gente inteligente". Então no final de 2019 tomei a decisão mais importante da minha vida profissional, entrar de cabeça no mundo da programação. 
Me inscrevi na faculdade.
Comecei a aprender o básico necessário.
Estipulei metas e coloquei na cabeça, ESSE ANO EU VOU ME TORNAR PROGRAMADOR.
E mesmo com o COVID meu sonho não mudou, atualmente passo cerca de 8 horas diárias estudando e procurando uma oportunidade para demonstrar meu potencial nesse mercado. 
Eu vou me tornar um programador, é só questão de tempo! 
😄 
## Outras Informações

Período Integral.
Meio período.
Posso me mudar.
Trabalho presencial e Home office.
Estudo HTML,CSS,JS e React.

## Skills

HTML,
CSS,
JS,
React,
Node,
MySQL,
SQLServer

## Contato

https://www.linkedin.com/in/matheus-f-4a5732b4/

**Comment by alinebastos** [comment]
OI @SaMatheus 
Sem as seções Áreas de Interesse e Tipo de contratação preenchidas não tem como eu colocar as labels, e fica mais dificil alguém olhar teu perfil.
Se tu puder arrumar isso pode te ajudar mais :)

**Comment by SaMatheus** [comment]
Olá @alinebastos , eu cheguei a colocar, mas não apareceu. Vou abrir outra para ver se aparece tá?
