### ISSUE TITLE
[João Pessoa/PB] Marcos Vinicius

### ISSUE THREAD

**Issue by markinascimento** [alinebastos/contrate-junior-estagio#174]
## Nome completo

Marcos Vinicius do Nascimento Santos

## Localidade

João Pessoa/PB

## Apresentação

Estudante de Ciências da Computação, apaixonado e entusiasta da tecnologia. Sempre estou a procura de novos desafios para poder provar a me mesmo que sou capaz de tudo, basta foco e determinação.

## Outras Informações

Disponível em horário comercial

## Skills

- Java
- JavaScript
- HTML
- CSS
- MySQL
- ReactJS
- React Native
- Scrum

## Áreas de Interesse

- [x ] Frontend
- [ ] Backend
- [ ] Fullstack
- [x ] Mobile
- [ ] UX
- [ ] DevOps
- [ ] Infra

## Contato

<!-- https://linkedin.com/in/marcoss-vinicius/

**Comment by alinebastos** [comment]
Oi @markinascimento preciso que tu complete teu cadastro colocando o tipo de contratação e principalmente o linkedin, senão não tem como as empreesas te contratarem e não tem como eu colocar as labels certas, ok? :)
