### ISSUE TITLE
[Petrópolis/RJ] Luiz Claudio

### ISSUE THREAD

**Issue by luizclaudiolc** [alinebastos/contrate-junior-estagio#246]
## Nome completo

Luiz Claudio Ribeiro Corrêa

## Localidade

Petrópolis-RJ

## Apresentação

Sou Luiz, descobri uma paixão por impactar vidas através do Desenvolvimento Web.

Em 2019, comecei estudar sobre Front-End e suas várias possibilidades de framesworks, e as possibilidades que vislumbrei me levaram a me especializar.

No início de 2020 tive a sorte de conseguir um bom curso através de um programa da Oracle, em parceria com plataforma de cursos online Alura, onde adquiri a formação em desenvolvimento Front-End, passeando desde a base, como: HTML, CSS, JavaScript, conhecendo framesworks como Jquery, Angular, Boostraps e adquirindo conhecimento em linguagem como Java.

Hoje, continuo a me desenvolver e estudando Java e aprendendo cada dia mais sobre o framework Vue.Js e estou adorando, aprender algo novo é sempre bom.

## Outras Informações

Estou disponível para mudanças, aceito trabalhos freelance e remoto, afinal, quanto mais trabalhamos, mais aprendemos.
Gosto de me desafiar, por isso participo de Hackathons, o último que participei foi da Sony Music, realizado de Shawee, e juntamente com isso estou sempre buscando e participando de Meetups, palestras e buscando mais conhecimento através de bootscamps.

## Skills

- JavaScript
- HTML
- CSS
- Bootstrap
- Swiper
- Jquery
- Java
- Sass
- Less
- Git e Github
- vue.js
- VS Code

## Áreas de Interesse
- [x] Frontend
- [x] Backend
- [x] Fullstack
- [ ] Mobile
- [ ] UX
- [ ] DevOps
- [x] Infra
-->

## Tipo de contratação

<!--
- [x] PJ
- [x] CLT
- [x] Estágio
- [x] Júnior
- [x] Freela

## Contato

https://www.linkedin.com/in/lclaudiolc/

**Comment by alinebastos** [comment]
Coloca o Linkedin, por favor :)
