### ISSUE TITLE
[Belo Horizonte/MG] Klecia Vladmaker

### ISSUE THREAD

**Issue by kleciavladmaker** [alinebastos/contrate-junior-estagio#248]
## Nome completo

Klecia Vladmaker Caldas

## Localidade

Belo Horizonte - Minas Gerais

## Apresentação

Cursando o 5º período de Sistemas de Informação pela Newton Paiva.
Apaixonada pela área de desenvolvimento, larguei o estágio de suporte para me dedicar mais aos estudos de programação. Nesse tempo consegui um estágio para programação em Java na Drogaria Araújo (conceituada rede de farmácias em MG), no estágio pude aprender como funciona a rotina de trabalho de um desenvolvedor e como funcionam os sistemas da empresa.
Atualmente busco um estágio em uma empresa de tecnologia para poder me desenvolver mais.

## Outras Informações

Tenho disponibilidade para trabalhar nos períodos da manhã e tarde.

## Skills

- Java
- Spring Boot
- Web Services
- Git/GitHub
- Banco de dados MYSQL/SQLSERVER
- HTML
- CSS
- JavaScript

## Áreas de Interesse

- [ ] Frontend
- [ ] Backend
- [x] Fullstack
- [ ] Mobile
- [ ] UX
- [ ] DevOps
- [ ] Infra

## Tipo de contratação

- [ ] PJ
- [x] CLT
- [x] Estágio
- [x] Júnior
- [x] Freela

## Contato

https://linkedin.com/in/kleciavladmaker

## Site

https://github.com/kleciavladmaker

**Comment by alinebastos** [comment]
Teu perfil do linkedin não está visível, está indisponivel, arruma isso pra gente?

**Comment by kleciavladmaker** [comment]
> Teu perfil do linkedin não está visível, está indisponivel, arruma isso pra gente?

Corrigido. Obrigada!
