### ISSUE TITLE
[São Paulo/SP] Julia Valerio

### ISSUE THREAD

**Issue by JuliaValerio** [alinebastos/contrate-junior-estagio#25]
## Nome completo

Julia Valerio Andrade Dias

## Localidade

 São paulo / SP

## Apresentação

Sou apaixonada por programação. Estudo Front-End por conta própria desde 2018 e em Julho do mesmo ano participei do curso de introdução a programação do coletivo Minas programam, que foi criada para desafiar os estereótipos de gênero e de raça que influenciam nossa relação com as áreas de ciências, tecnologia e computação.
E em março de 2019, tranquei a faculdade para fazer o bootcamp intensivo de fron-end na {Reprograma} onde pude aprofundar, aprimorar e adquirir novos conhecimentos. Sou entusiasta de Javascript, busco sempre praticar e aprender novas tecnologias sem esquecer das bases.

## Outras Informações

Nesse momento tenho disponibilidade para trabalhos remotos, e em SP. 

## Skills

- JavaScript
- HTML
- CSS
- SASS
- GIT 
- React.js
- Vue.js
- Bootstrap
- Noções de UX
- SCRUM
- Jira

## O que está procurando

- Júnior

## Tipo de contratação

- PJ
- CLT

## Contato

https://www.linkedin.com/in/julia-val%C3%A9rio-331195101/

## Site

https://juliavalerio.github.io/

**Comment by marciafc** [comment]
@JuliaValerio infelizmente teremos que fechar tua issue. Conforme regras do repositório, somente serão aceitos perfis que estão em busca da primeira oportunidade. Do contrário, teríamos que abrir exceção para outros perfis  :-(
