### ISSUE TITLE
[São Paulo/SP] Alexandre Souza

### ISSUE THREAD

**Issue by AlehSouza** [alinebastos/contrate-junior-estagio#43]
## Nome completo

Alexandre Henrique Gabino de Souza

## Localidade

São Paulo - SP

## Apresentação

Olá, me chamo Alexandre, sou da zona leste de São Paulo, curso faculdade na Fatec de Ferraz, possuo uma breve experiência no mercado de trabalho, e tenho como objetivo me profissionalizar como Desenvolvedor Front-End.

## Outras Informações

Disponibilidade de Horário: Vespertino

## Skills

- CSS
- HTML
- JavaScript
- Vue
- Node

## O que está procurando

- Estágio 
- Junior

## Tipo de contratação

- CLT
- Estágio

## Contato

https://www.linkedin.com/in/alesouza2503/

**Comment by alinebastos** [comment]
@AlehSouza eu tenho que fechar essa issue, espero que tu entenda, mas esta iniciativa é para quem tem zero experiencia no mercado, como está descrito no README, para quem está buscando a primeira experiencia.
