### ISSUE TITLE
[São PAULO / SP] - Bruno Pessoa

### ISSUE THREAD

**Issue by brunopeople** [alinebastos/contrate-junior-estagio#64]
## Nome completo
Bruno Pessoa Nunes De Melo

## Localidade

SP/ São Paulo

## Apresentação
Formado em bacharelado em Engenharia da Computação pela UNP, minhas primeiras experiências na área de T.I foram como
estagiário exercendo a função de Help Desk, Administrador de Redes, Cabeamentro Estruturado, Registro de Chamadas e Resoluções. Após o término da graduação gostaria de ingrenssar na área de Desenvolvimento Web, então eu fiz alguns cursos técnico online da Alura e Udemy para está atualizado as demandas deste mercado de trabalho. Minha ultima experiência foi Web Developer PHP contrado como PJ na empresa Sin Solution para desenvolver aplicações e fazer manutenção de sistemas da própria empresa e de clientes. Devido a pandemia fui desligado da empresa, então eu estou até hoje a procura de oportunidade para crescer como profissional.

## O que está procurando

- Júnior
- Freela

## Tipo de contratação

- PJ
- CLT
- Freela

## Contato

- https://www.linkedin.com/in/bruno-pessoa-a3752484/

## Site

- 
[curriculo_de_bruno_pessoa_nunes_de_melo_criado_em_11_09_20_as_qwdEc_minha_pagina_inicial.pdf](https://github.com/alinebastos/contrate-junior-estagio/files/5550083/curriculo_de_bruno_pessoa_nunes_de_melo_criado_em_11_09_20_as_qwdEc_minha_pagina_inicial.pdf)
https://app.netlify.com/teams/brunopeople/overview

**Comment by alinebastos** [comment]
Tu já tem experiência na área, esta iniciativa é para quem está procurando a sua primeira! Por isso foi fechada a issue e será fechada novamente ;)

**Comment by brunopeople** [comment]
Então, foi uma experiência de 1 mês que infelizmente foi  terminada por causa da pandemia da covid. Muitos falam que quase não conta, eu preciso de uma oportunidade.

**Comment by alinebastos** [comment]
Pois é, outras pessoas também me pediram para abrir uma exceção, imagina se eu começo a abrir exceção para todos? Que régua vou usar para essa exceção? Sendo que tem muita gente aí que não teve UMA chancezinha ainda.
E está no README, bem grande, que perfis com experiencia a issue seria fechada.
Se eu abro uma exceção pra ti isso abre um precedente que eu não tenho como controlar depois =/
Espero que tu entenda.
