### ISSUE TITLE
Ramon Fernandes

### ISSUE THREAD

**Issue by RamonFern** [alinebastos/contrate-junior-estagio#66]
<!--
  ============================
  ATENÇÃO:
  1) Remova os comentários HTML e preencha com os seus dados.

  2) Não divulgue aqui seu e-mail pessoal e telefone, pois as informações
  abaixo são públicas. Deixe apenas o seu Linkedin para que as empresas
  possam entrar em contato.

  3) Para as opções, mantenha a marcação que se adequa as suas habilidades e remova as que não fazem sentido.
  
    Por exemplo:

  - PJ
  - CLT
  - Freela
  - Estágio

  Se você quiser trabalhar somente como CLT, mantenha apenas essa opção.
  
  IMPORTANTE: Para visualizar se está tudo correto, antes de publicar seu perfil, clique na 
  aba "Preview".

  4) Não esqueça de colocar cidade/estado no título, seguindo o padrão:
  [Rosário/MA] Ramon Fernandes
 Ramon Fernandes 

## Localidade

 Rosário-MA

## Apresentação

Sou estudante de Java

## Outras Informações

Disponível para todos os horários e também para viagem

## Skill##

- Java e Quarkus
- HTML
- CSS
- Spring Boot
- SQL

## O que está procurando

- Estágio
- Júnior

## Tipo de contratação

- PJ
- CLT
- Estágio

## Contato
(98) 98143-9023
ramonfernandes9@gmail.com
https://www.linkedin.com/in/ramon-fernandes-652b76b0 

## Site

https://github.com/RamonFern

**Comment by alinebastos** [comment]
oi @RamonFern tu podes descomentar as tuas respostas? Elas não estão aparecendo :)

**Comment by alinebastos** [comment]
Vamos deixar a issue fechada até tu arrumar? :)

**Comment by RamonFern** [comment]
oi não consigo corriger se não abrir.

**Comment by RamonFern** [comment]
oi boa noite
vê se ta certo agora

**Comment by RamonFern** [comment]
oi boa noite
acredito que agora esta certo. 
vc pode reabrir?
