### ISSUE TITLE
Poá - São Paulo | Camila D'Amato

### ISSUE THREAD

**Issue by damato1** [alinebastos/contrate-junior-estagio#69]
[LINKEDIN: Camila D'Amato](https://www.linkedin.com/mwlite/in/camila-d-amato-1909161ba)

**Comment by alinebastos** [comment]
Oi @damato1 :)
Tu pode deixar o teu perfil conforme o template que foi criado?
Vou deixar a issue fechada enquanto isso, aí depois tu reabre, pode ser?
Bjos!
