### ISSUE TITLE
[Mairiporã/SP]Cristiane Pereira

### ISSUE THREAD

**Issue by Cristiane-Pereira** [alinebastos/contrate-junior-estagio#76]
Nome:Cristiane Pereira da silva.

Localidade:Mairiporã -SP

##Apresentação

Olá,me chamo Cristiane,tenho 30 anos e recentimente estou cursando Programação e em breve estarei me tornado uma desenvolvedora full stack, sou uma pessoa dedicada,auto motivada e apaixonada por programação e tecnologia,possuo grande proficiência em Html,Css,javascript,framework Bootstraap e Php,desenvolvo meus códigos  de forma limpa e eficiente. Confortável em trabalhar como parte de uma equipe ou solo,Procuro uma oportunidade de vaga permanente  ou Temporária  em uma empresa na qual eu possa trabalhar como desenvolvedora front-end e desenvolver minhas aplicações com Qualidade e eficiência.

## Skills

- HTML5
- CSS3
- JavaScript 
- PHP
- mySQL
- Framework Bootstraap 
- Versionamento Git
- Wordpress 

## O que está procurando

- Estágio
- Júnior
- Freela

## Tipo de contratação

- CLT
- Freela
- Estágio

## Contato

linkedin.com/in/cristiane-pereirasilva 

## Site

github.com/Cristiane-Pereira

**Comment by alinebastos** [comment]
Oi @Cristiane-Pereira 
Tu pode ajeitar teu perfil como no template? O linkedin e o github não estão como links, o que dificulta pra quem quer ver teu perfil :)
Vou fechar a issue, ai quando tu arrumar tu reabre, pode ser?
Bjos!
