### ISSUE TITLE
[Joinville, Santa Catarina] - Ezequiel Gnich

### ISSUE THREAD

**Issue by EzequielGnich** [alinebastos/contrate-junior-estagio#83]
## Nome completo

Ezequiel Gnich

## Localidade

[Joinville, Santa Catarina]

## Apresentação

Recentemente me formei em análise e desenvolvimento de sistemas pela Unopar e estou trabalhando em um projeto para uma empresa de Itapema desenvolvendo partes de um app, também possuo alguns cursos na área de desenvolvimento feitos pela Udemy e Hotmart:

**DESENVOLVIMENTO WEB - HTML, CSS, Bootstrap, JavaScript, JQuery, PHP, 
POO e MySQL** - *www.udemy.com.br*

**REACT + REDUX - WEBPACK, REDUX-FORM, MONGODB, EXPRESS, NODE** - *www.udemy.com.br*

**FULLSTACK DEVELOPER** - *www.devpleno.com*

**GraphQL: Criando APIs Profissionais e Flexíveis** - *https://www.udemy.com/certificate/UC-87568cf2-d631-40bc-ad5d-5e19eb46d3b1/*

**Do Zero ao Redux - projetos práticos diversificados** - *https://www.udemy.com/certificate/UC-0cdfe7f9-3c84-44e6-a86a-12cc0dc772c6/*

**Curso React + Redux: Fundamentos e 2 Apps do Absoluto ZERO!** - *https://www.udemy.com/certificate/UC-5JD8QEGB/*

## Outras Informações

- Estou disponível para trabalhar em qualquer horário, mudanças (dependendo da oferta e local) e viagens.

## Skills

- HTML
- CSS
- Javascript
- ReactJS
- React Native
- NodeJS
- NoSQL
- SQL
- Git

## O que está procurando

- Júnior
- Freela

## Tipo de contratação

- PJ
- CLT
- Freela

## Contato

https://linkedin.com/in/ezequielgnich

## Portfólio

https://github.com/EzequielGnich

**Comment by alinebastos** [comment]
"estou trabalhando em um projeto para uma empresa de Itapema desenvolvendo partes de um app"
Este repositório é para quem nunca teve experiência e está procurando a sua primeira, por isso vou fechar a issue, ok?

**Comment by EzequielGnich** [comment]
Eu não tenho experiência, faz um mês que estou buscando alguma coisa e consegui ali, mas não é garantido a permanência na vaga. Mas tudo bem.
