### ISSUE TITLE
[Cuiabá/MT] Douglas Frota Brandão

### ISSUE THREAD

**Issue by douglasbrandao** [alinebastos/contrate-junior-estagio#86]
## Nome completo

Douglas Frota Brandão

## Localidade

Cuiabá / MT

## Apresentação

Estudante de Engenharia da Computação no Instituto Federal de Mato Grosso desde 2015, tive a oportunidade de aprender sobre diversas áreas dentro da Computação desde Programação baixo nível e Redes a me apaixonar pelo desenvolvimento de aplicações web após me envolver em um projeto de pesquisa onde utilizei ferramentas como Python, Django e JavaScript com a finalidade de desenvolver uma aplicação web gamificada para uso de Professores. Tive também uma experiência de estágio dentro da Reitoria do próprio Instituto onde desenvolvi aplicações para uso de bibliotecários e jogos estudantis. Atualmente estou terminando o último semestre da faculdade e me envolvendo cada vez mais dentro do mundo web criando alguns projetos com React.js. Tenho Inglês Intermediário.

## Outras Informações

Segundas e Terça - Dia todo;
Quartas, Quintas e Sextas - Aulas no período da manhã e tarde livre;
Possibilidade para trabalho remoto;

## Skills

- HTML
- Python
- Django
- CSS
- Django Rest Framework
- JavaScript
- GIT
- React
- React Native
- Flask

## O que está procurando

- Estágio
- Júnior
- Freela

## Tipo de contratação

- PJ
- CLT
- Freela
- Estágio

## Contato

https://www.linkedin.com/in/douglasfbrandao/

**Comment by douglasbrandao** [comment]
Teve alguma coisa errada com o template? Obrigado!

**Comment by alinebastos** [comment]
Obrigada por entender ❤️
